import {
  Apple,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Coffee,
  Droplet,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  KeyRound,
  Landmark,
  Laptop,
  Music,
  Package,
  Palette,
  PawPrint,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Tag,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Utensils,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon
} from 'lucide-react'
import { FALLBACK_ICON } from '../../shared/defaultCategories'

/** Die Namen stehen so in categories.json. Einträge umbenennen heißt gespeicherte Daten migrieren. */
export const categoryIcons: Record<string, LucideIcon> = {
  tag: Tag,
  home: House,
  key: KeyRound,
  zap: Zap,
  flame: Flame,
  droplet: Droplet,
  wifi: Wifi,
  smartphone: Smartphone,
  sofa: Sofa,
  wrench: Wrench,
  cart: ShoppingCart,
  apple: Apple,
  utensils: Utensils,
  coffee: Coffee,
  beer: Beer,
  train: TrainFront,
  bus: Bus,
  car: Car,
  fuel: Fuel,
  bike: Bike,
  plane: Plane,
  gamepad: Gamepad2,
  tv: Tv,
  film: Film,
  music: Music,
  ticket: Ticket,
  palette: Palette,
  book: BookOpen,
  dumbbell: Dumbbell,
  bag: ShoppingBag,
  shirt: Shirt,
  laptop: Laptop,
  gift: Gift,
  scissors: Scissors,
  heart: HeartPulse,
  pill: Pill,
  shield: Shield,
  baby: Baby,
  paw: PawPrint,
  graduation: GraduationCap,
  package: Package,
  receipt: Receipt,
  landmark: Landmark,
  briefcase: Briefcase,
  banknote: Banknote,
  coins: HandCoins,
  piggy: PiggyBank,
  trending: TrendingUp
}

export function CategoryIcon({ name, size = 16, className }: { name: string; size?: number; className?: string }) {
  const Icon = categoryIcons[name] ?? categoryIcons[FALLBACK_ICON]
  return <Icon size={size} strokeWidth={1.75} className={className} aria-hidden />
}
